import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ProductCard from "@/components/ProductCard";
import SectionTitle from "@/components/SectionTitle";
import {categories,products} from "@/lib/products";
export default function Home(){return <><Header/><main>
<section className="container relative overflow-hidden py-14 md:py-24"><div className="relative grid items-center gap-10 md:grid-cols-[1.15fr_.85fr]"><div><span className="inline-flex rounded-full border border-blue-400/20 bg-blue-500/10 px-4 py-2 text-xs font-bold text-blue-200">منصة رقمية سودانية • NURO STORE</span><h1 className="mt-6 text-4xl font-black leading-[1.15] md:text-6xl">كل عالمك الرقمي<br/><span className="text-blue-400">في مكان واحد</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-400 md:text-lg">اكتشف الاشتراكات، الألعاب، البطاقات والخدمات الرقمية في تجربة عربية حديثة وسريعة.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/shop" className="rounded-2xl bg-blue-500 px-7 py-4 font-bold">تصفح المتجر</Link><Link href="/categories" className="rounded-2xl border border-white/10 bg-white/5 px-7 py-4 font-bold">استكشف الأقسام</Link></div></div><div className="glass rounded-[2rem] p-5"><div className="product-art grid min-h-80 place-items-center rounded-[1.5rem]"><div className="text-center"><div className="mx-auto grid size-28 place-items-center rounded-[2rem] border border-blue-300/20 bg-blue-400/10 text-5xl font-black text-blue-200">N</div><div className="mt-5 text-xl font-black">NURO DIGITAL</div><div className="mt-2 text-sm text-slate-400">اشتراكات • ألعاب • بطاقات • خدمات</div></div></div></div></div></section>
<section className="container py-8"><SectionTitle eyebrow="CATEGORIES" title="تصفح حسب القسم"/><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{categories.map(c=><Link key={c.id} href={`/categories/${c.id}`} className="glass rounded-2xl p-5 hover:border-blue-400/30"><div className="mb-4 text-2xl text-blue-300">{c.icon}</div><div className="font-bold">{c.name}</div><div className="mt-1 text-xs text-slate-500">منتجات رقمية</div></Link>)}</div></section>
<section className="container py-14"><SectionTitle eyebrow="FEATURED" title="منتجات مختارة" description="مجموعة من المنتجات الرقمية الجاهزة للطلب."/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(15,23).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
<section className="container py-8"><div className="glass rounded-[2rem] p-8 md:p-12"><div className="max-w-2xl"><div className="text-xs font-bold text-blue-300">NURO STORE</div><h2 className="mt-3 text-3xl font-black">تجربة شراء رقمية بسيطة</h2><p className="mt-4 leading-8 text-slate-400">اختر المنتج، أضفه للسلة، ثم أكمل بيانات الطلب. الأسعار غير معروضة داخل قالب المتجر، وتأكيد الطلب يتم عبر قنوات التواصل.</p><Link href="/shop" className="mt-7 inline-block rounded-xl bg-blue-500 px-6 py-3 font-bold">ابدأ الآن</Link></div></div></section>
</main><Footer/></>}