"use client";
import Link from "next/link";
import {Heart,ShoppingCart,Check} from "lucide-react";
import type {Product} from "@/lib/products";
import {useEffect,useState} from "react";
export default function ProductCard({product}:{product:Product}){
 const[fav,setFav]=useState(false),[added,setAdded]=useState(false);
 useEffect(()=>{try{setFav(JSON.parse(localStorage.getItem("nuro-favorites")||"[]").includes(product.id))}catch{}},[product.id]);
 const toggle=()=>{const old=JSON.parse(localStorage.getItem("nuro-favorites")||"[]");const next=old.includes(product.id)?old.filter((x:string)=>x!==product.id):[...old,product.id];localStorage.setItem("nuro-favorites",JSON.stringify(next));setFav(next.includes(product.id));window.dispatchEvent(new Event("storage"))};
 const add=()=>{const old=JSON.parse(localStorage.getItem("nuro-cart")||"[]");const i=old.findIndex((x:any)=>x.id===product.id);const next=i>=0?old.map((x:any,j:number)=>j===i?{...x,qty:(x.qty||1)+1}:x):[...old,{id:product.id,qty:1}];localStorage.setItem("nuro-cart",JSON.stringify(next));setAdded(true);window.dispatchEvent(new Event("storage"));setTimeout(()=>setAdded(false),1000)};
 return <article className="glass group overflow-hidden rounded-3xl transition hover:-translate-y-1 hover:border-blue-400/30"><Link href={"/product/"+product.id}><div className="product-art relative grid aspect-[4/3] place-items-center">{product.badge&&<span className="absolute right-3 top-3 rounded-full bg-blue-500/20 px-3 py-1 text-[11px] font-bold text-blue-200">{product.badge}</span>}<div className="grid size-24 place-items-center rounded-3xl border border-blue-300/20 bg-blue-400/10 text-3xl font-black text-blue-200 shadow-[0_0_45px_rgba(22,136,255,.2)]">{product.icon}</div></div></Link><div className="p-5"><div className="mb-2 text-xs text-blue-300">{product.category}</div><Link href={"/product/"+product.id} className="block text-lg font-bold hover:text-blue-300">{product.name}</Link><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-400">{product.description}</p><div className="mt-5 flex gap-2"><button aria-label="المفضلة" onClick={toggle} className="grid size-11 place-items-center rounded-xl border border-white/10 bg-white/5"><Heart size={17} className={fav?"fill-blue-400 text-blue-400":""}/></button><button onClick={add} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-blue-500 px-4 py-3 text-sm font-bold">{added?<><Check size={17}/> تمت الإضافة</>:<><ShoppingCart size={17}/> أضف للسلة</>}</button></div></div></article>
}